[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev"
  port = 4321

# Password protection for sub-sites
[context.production]
  [context.production.environment]
    SITE_PASSWORD = "your_secure_password_here"

# Headers to allow embedding in main site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self' https://gridstoranalytics.com https://*.gridstoranalytics.com"

# Catch-all redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 